import type { BlueprintDefinition } from './index.js';

/**
 * Counter-Strike 2, on `joedwards32/cs2`.
 *
 * The only blueprint here with no world to lose: CS2 keeps nothing across a restart except its
 * configuration, so the stop path is a plain signal and the disk requirement is all game files.
 */
export const counterStrike2Blueprint: BlueprintDefinition = {
  key: 'counter-strike-2',
  name: 'Counter-Strike 2',
  game: 'Counter-Strike 2',
  summary: 'Valve competitive shooter. Modest memory, 60 GB of game files.',
  description: [
    'A Counter-Strike 2 dedicated server. Memory is the easy part — 4 GB is comfortable — but',
    'the game files are around 60 GB, so give it disk.',
    '',
    'A Game Server Login Token is required for anyone outside your LAN to connect. Generate one',
    'at steamcommunity.com/dev/managegameservers for app 730 and paste it below; without it the',
    'server runs but only answers on the local network.',
    '',
    'Administration is over RCON, which is also how Platter reads the player list. There is no',
    'world to corrupt, so stopping is just a signal.',
  ].join(' '),
  category: 'shooter',
  image: 'joedwards32/cs2:4.0.1',
  icon: { monogram: 'CS', hue: 44, glyph: 'crosshair' },
  minMemoryMb: 2048,
  recommendedMemoryMb: 4096,
  minDiskMb: 61440,
  ports: [
    { name: 'game', label: 'Game', containerPort: 27015, protocol: 'udp', primary: true },
    { name: 'rcon', label: 'RCON', containerPort: 27015, protocol: 'tcp', bindLocal: true },
    { name: 'tv', label: 'CSTV', containerPort: 27020, protocol: 'udp' },
  ],
  variables: [
    {
      key: 'CS2_SERVERNAME',
      label: 'Server name',
      type: 'string',
      default: 'Platter',
      min: 1,
      max: 64,
    },
    {
      key: 'SRCDS_TOKEN',
      label: 'Game Server Login Token',
      description:
        'From steamcommunity.com/dev/managegameservers, app id 730. Required for anyone outside your local network to connect.',
      type: 'password',
      default: '',
      max: 64,
      pattern: '^[A-Za-z0-9]*$',
    },
    {
      key: 'CS2_RCONPW',
      label: 'RCON password',
      description: 'Required for the console, scheduled commands and the player list.',
      type: 'password',
      default: null,
      required: true,
      min: 8,
      max: 64,
    },
    {
      key: 'CS2_PW',
      label: 'Server password',
      description: 'Leave empty for an open server.',
      type: 'password',
      default: '',
      max: 64,
    },
    {
      key: 'CS2_MAXPLAYERS',
      label: 'Player slots',
      type: 'number',
      default: 10,
      min: 2,
      max: 64,
    },
    {
      key: 'CS2_GAMEALIAS',
      label: 'Game mode',
      description: 'Sets the game type and mode together. Leave empty to set them individually.',
      type: 'enum',
      default: 'competitive',
      options: [
        { value: '', label: 'Set game type and mode manually' },
        { value: 'casual', label: 'Casual' },
        { value: 'competitive', label: 'Competitive' },
        { value: 'wingman', label: 'Wingman (2v2)' },
        { value: 'deathmatch', label: 'Deathmatch' },
        { value: 'armsrace', label: 'Arms Race' },
        { value: 'custom', label: 'Custom' },
      ],
    },
    {
      key: 'CS2_STARTMAP',
      label: 'Starting map',
      type: 'string',
      default: 'de_inferno',
      max: 64,
      pattern: '^[A-Za-z0-9_]+$',
    },
    {
      key: 'CS2_MAPGROUP',
      label: 'Map group',
      description: 'Which map pool the server rotates through.',
      type: 'string',
      default: 'mg_active',
      max: 64,
      advanced: true,
    },
    {
      key: 'CS2_SERVER_HIBERNATE',
      label: 'Hibernate when empty',
      description: 'Drops CPU use to nearly nothing while nobody is connected.',
      type: 'boolean',
      default: true,
    },
    {
      key: 'CS2_BOT_QUOTA',
      label: 'Bot count',
      description: 'Leave empty for the game mode default.',
      type: 'string',
      default: '',
      max: 3,
      pattern: '^\\d*$',
      advanced: true,
    },
    {
      key: 'CS2_BOT_DIFFICULTY',
      label: 'Bot difficulty',
      type: 'enum',
      default: '',
      options: [
        { value: '', label: 'Game mode default' },
        { value: '0', label: 'Easy' },
        { value: '1', label: 'Normal' },
        { value: '2', label: 'Hard' },
        { value: '3', label: 'Expert' },
      ],
      advanced: true,
    },
    {
      key: 'CS2_CHEATS',
      label: 'Enable cheats',
      description: 'sv_cheats. Useful for practice servers, disastrous on a public one.',
      type: 'boolean',
      default: false,
      advanced: true,
    },
    {
      key: 'CS2_LAN',
      label: 'LAN mode',
      description: 'No Steam authentication and no token needed, but only reachable locally.',
      type: 'boolean',
      default: false,
      advanced: true,
    },
    {
      key: 'TV_ENABLE',
      label: 'Enable CSTV',
      description: 'Lets spectators watch on a delay through the CSTV port.',
      type: 'boolean',
      default: false,
      advanced: true,
    },
    {
      key: 'CS2_ADDITIONAL_ARGS',
      label: 'Extra launch arguments',
      type: 'string',
      default: '',
      max: 400,
      advanced: true,
    },
    {
      key: 'STEAMAPPVALIDATE',
      label: 'Validate game files on start',
      description: 'Slower start, but repairs a corrupted install. Turn on once, then off again.',
      type: 'boolean',
      default: false,
      advanced: true,
    },

    // Fixed by the blueprint: these have to agree with `ports` above.
    { key: 'CS2_PORT', label: 'Game port', type: 'number', default: 27015, hidden: true },
    { key: 'TV_PORT', label: 'CSTV port', type: 'number', default: 27020, hidden: true },
  ],
  signals: {
    ready: ['Connection to Steam servers successful', 'Host activate: Changelevel'],
    crash: [
      'Segmentation fault',
      'Engine Error',
      'Host_Error',
      'FATAL:',
      'Failed to load the launcher',
    ],
    // Source's log format: `"Name<2><[U:1:1234]><>" connected, address "1.2.3.4:27005"`.
    // Group 1 is the display name.
    playerJoin: ['"(.+?)<\\d+><\\[U:\\d+:\\d+\\]><[^>]*>" connected'],
    playerLeave: ['"(.+?)<\\d+><\\[U:\\d+:\\d+\\]><[^>]*>" disconnected'],
  },
  stop: {
    // Nothing persistent to flush — CS2 keeps no world — so a signal is both correct and fast.
    strategy: 'signal',
    command: null,
    signal: 'SIGTERM',
    timeoutSeconds: 30,
  },
  dataPath: '/home/steam/cs2-dedicated',
  features: { console: false, rcon: true, mods: false, worldUpload: false, playerList: true },
  docsUrl: 'https://github.com/joedwards32/CS2',
};
