/**
 * `@platter/mods` — mod discovery and compatibility.
 *
 * The intended entry point is `ModRegistry`: it fans a search across whichever providers are
 * configured and turns a project reference into a specific file with a verdict attached. The
 * provider clients and `checkCompatibility` are exported alongside it because the MCP server and
 * the diagnostics package need them directly, and because a pure, synchronous compatibility
 * check is worth being able to call without constructing anything.
 */

export {
  type CompatInput,
  type CompatReport,
  type ConflictRef,
  checkCompatibility,
  compareGameVersions,
  type DependencyPlan,
  type DependencyPlanNode,
  type DependencyResolution,
  type DependencyResolver,
  dependencyKey,
  type Finding,
  type InstalledMod,
  NEOFORGE_FORGE_BRIDGE_VERSION,
  type ResolveGraphInput,
  resolveDependencyGraph,
  SINGLETON_ROLES,
  type TargetServer,
  type UnresolvedDependency,
  type Verdict,
} from './compat';
export {
  CLASS_ID,
  CURSEFORGE_BASE_URL,
  CURSEFORGE_MAX_PAGE_SIZE,
  CURSEFORGE_MAX_RESULT_WINDOW,
  CurseForgeClient,
  type CurseForgeClientOptions,
  type CurseForgeFileWire,
  type CurseForgeModWire,
  checkPageBounds,
  downloadState,
  ENVIRONMENT_VERSION_TYPE_ID,
  environmentTagsOf,
  gameVersionsOf,
  LOADER_VERSION_TYPE_ID,
  loadersOf,
  MINECRAFT_GAME_ID,
  MOD_LOADER_TYPE,
  modLoaderTypeFor,
  normaliseFile,
  normaliseMod,
  RELATION_TYPE_TO_KIND,
} from './curseforge';
export {
  HttpClient,
  type HttpClientOptions,
  PLATTER_VERSION,
  type RequestOptions,
  TokenBucket,
  TtlCache,
  USER_AGENT,
} from './http';
export {
  buildFacets,
  encodeArrayParam,
  FALLBACK_LOADER_NAMES,
  MODRINTH_BASE_URL,
  MODRINTH_FACET_FIELDS,
  MODRINTH_MAX_LIMIT,
  MODRINTH_RATE_LIMIT,
  ModrinthClient,
  type ModrinthClientOptions,
  type ModrinthProjectWire,
  type ModrinthSearchHitWire,
  type ModrinthVersionWire,
  normaliseProject,
  normaliseSearchHit,
  normaliseVersion,
  partitionCategories,
  validateFacet,
} from './modrinth';
export {
  acceptedLoaders,
  ModRegistry,
  type ModRegistryOptions,
  type ResolvedForServer,
  type ResolveOptions,
} from './registry';
export {
  type DependencyRef,
  dependencyRefSchema,
  deriveEnvironment,
  environmentToSides,
  MOD_ENVIRONMENTS,
  type ModEnvironment,
  type ModFile,
  type ModProject,
  type ModSearchQuery,
  type ModSearchResult,
  type ModSort,
  type ModVersion,
  modEnvironmentSchema,
  modFileSchema,
  modProjectSchema,
  modSearchQuerySchema,
  modSearchResultSchema,
  modVersionSchema,
  normaliseLoaderName,
  type ProviderAvailability,
  type ProviderClient,
  parseQualifiedId,
  qualifiedId,
  type ReleaseChannel,
  type ResolvedModSearchQuery,
  releaseChannelSchema,
  serverSideOf,
  type VersionFilter,
} from './types';
